Load rmq-forwarder config from SSM
snap40/rabbit-amazon-forwarder pull request #1
Opened 2023-03-23 16:18 UTC by ruthtaunton

Added a SSM loader (which could be refactored out into it's own repo in the future, for other Go binaries to load from SSM using standard Current Health paths).

Updated config.go to first try to load the config from SSM, before trying the previous options of Vault and a local file.

2023-03-27 08:31 UTC, jimcroft reviewed
Would prefer internal consistency than consistency with the Config-Manager Java library.

2023-03-27 08:31 UTC, jimcroft commented on config/ssm_loader.go
> +	}
This approach is lifted from the Config-Manager. That makes sense in our Java services where each service tends to fetch a load of config keys across stage, service, etc. paths.

This service is much simpler and loads a single blob of JSON config. When loading from a file that file is defined by the `MAPPING_FILE` environment variable, when loading from Vault that path is defined by the `VAULT_PATH` environment variable.

I'm not sure making SSM loading behave like our Java services but completely differently to the other config loading mechanisms in this service makes sense.

Ideally I think I'd prefer to see us just load from `SSM_PATH` for internal consistency rather than follow the Config-Manager approach.

2023-04-20 10:27 UTC, jimcroft requested changes

2023-04-20 10:27 UTC, jimcroft commented on config/ssm_loader.go
> +	    log.Info("Loaded property " + path + "=" + value + " from SSM")
This looks like it'll log the whole config blob. The config will include auth credentials for RabbitMQ and we def don't want them logged. I would remove this log line.

2023-04-20 16:00 UTC, ruthtaunton commented on config/ssm_loader.go
> +	    log.Info("Loaded property " + path + "=" + value + " from SSM")
Thanks for spotting, fixed

2023-04-21 08:29 UTC, jimcroft requested changes
Looks good to me except for one issue in `config.Load()`.

2023-04-21 08:29 UTC, jimcroft commented on config/config.go
> +		log.Info("loading source/destination from SSM failed, falling back to local file, err:", err.Error())
Can we maintain the same pattern here for choosing which config loading method to use?

ie. Don't assume we're loading from SSM. Check if `ssmPath` is set before trying to load from SSM, like we do with vault and file configs.

2023-04-21 11:09 UTC, ruthtaunton commented on config/config.go
> +		log.Info("loading source/destination from SSM failed, falling back to local file, err:", err.Error())
Done

2023-04-21 11:09 UTC, jimcroft approved these changes
:shipit:

2023-04-21 11:10 UTC, merged